Changed from "if always()" to "if !cancelled()" in workflow files, to allow cancelling running workflows. Temporary disabled CI steps for quick testing.

diff --git a/.github/workflows/ci_linux.yml b/.github/workflows/ci_linux.yml
--- a/.github/workflows/ci_linux.yml
+++ b/.github/workflows/ci_linux.yml
@@ -74,133 +74,133 @@ jobs:
         ./gambit -rf yaml_files/spartan.yaml 
 
 
-  backends_build:
-    needs: [pre_job, gambit_build] # Sets run order
-    if: ${{ always() && needs.pre_job.outputs.should_skip != 'true' }}
-    runs-on: [self-hosted, Linux, X64]
-    strategy:
-      fail-fast: false
-      matrix:
-        arch: [X64]
-    defaults:
-      run:
-        shell: bash -eo pipefail {0}
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v2
-    - name: Set up build environment
-      run: |
-        echo "Set up the build environment"
-        mkdir -p BUILD
-        cd BUILD
-        # The 'patch' tool is not installed system-wide on Wino, so we have our own installation of it:
-        alias patch=/mn/fys-server1/a9/anderkve/tools/patch/bin/patch
-    - name: Configure with cmake
-      run: |
-        echo "Configure with cmake"
-        cd BUILD
-        cmake -DPYTHON_LIBRARY=/usr/lib64/libpython3.9.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.9 -DWITH_MPI=ON -DWITH_HEPMC=ON -DBUILD_FS_MODELS="CMSSM;MSSM;MDM" -Ditch="great" -DEIGEN3_INCLUDE_DIR=/mn/fys-server1/a1/chrichan/Packages/Eigen/eigen3 ..
-    - name: Build Backends
-      run: |
-        echo "Building all Backends"
-        cd BUILD
-        # Build backends, except those that are tested via other jobs.
-        # This replaces the "make backends" command.
-        ../cmake/scripts/build_backends.sh -f default_backends.txt -j 1 -s "nulike susyhit rivet contur pythia higgsbounds higgssignals ATLAS_FullLikes superiso heplikedata heplike" 
+  # backends_build:
+  #   needs: [pre_job, gambit_build] # Sets run order
+  #   if: ${{ !cancelled() && needs.pre_job.outputs.should_skip != 'true' }}
+  #   runs-on: [self-hosted, Linux, X64]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       arch: [X64]
+  #   defaults:
+  #     run:
+  #       shell: bash -eo pipefail {0}
+  #   steps:
+  #   - name: Checkout
+  #     uses: actions/checkout@v2
+  #   - name: Set up build environment
+  #     run: |
+  #       echo "Set up the build environment"
+  #       mkdir -p BUILD
+  #       cd BUILD
+  #       # The 'patch' tool is not installed system-wide on Wino, so we have our own installation of it:
+  #       alias patch=/mn/fys-server1/a9/anderkve/tools/patch/bin/patch
+  #   - name: Configure with cmake
+  #     run: |
+  #       echo "Configure with cmake"
+  #       cd BUILD
+  #       cmake -DPYTHON_LIBRARY=/usr/lib64/libpython3.9.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.9 -DWITH_MPI=ON -DWITH_HEPMC=ON -DBUILD_FS_MODELS="CMSSM;MSSM;MDM" -Ditch="great" -DEIGEN3_INCLUDE_DIR=/mn/fys-server1/a1/chrichan/Packages/Eigen/eigen3 ..
+  #   - name: Build Backends
+  #     run: |
+  #       echo "Building all Backends"
+  #       cd BUILD
+  #       # Build backends, except those that are tested via other jobs.
+  #       # This replaces the "make backends" command.
+  #       ../cmake/scripts/build_backends.sh -f default_backends.txt -j 1 -s "nulike susyhit rivet contur pythia higgsbounds higgssignals ATLAS_FullLikes superiso heplikedata heplike" 
 
 
-  test_runs:
-    needs: [pre_job, gambit_build, backends_build] # Sets run order
-    if: ${{ always() && needs.pre_job.outputs.should_skip != 'true' }}
-    runs-on: [self-hosted, Linux, X64]
-    strategy:
-      fail-fast: false
-      matrix:
-        arch: [X64]
-    defaults:
-      run:
-        shell: bash -eo pipefail {0}
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v2
-    - name: Set up build environment
-      run: |
-        echo "Set up the build environment"
-        mkdir -p BUILD
-        cd BUILD
-        # The 'patch' tool is not installed system-wide on Wino, so we have our own installation of it:
-        alias patch=/mn/fys-server1/a9/anderkve/tools/patch/bin/patch
-    - name: Configure with cmake
-      run: |
-        echo "Configure with cmake"
-        cd BUILD
-        cmake -DPYTHON_LIBRARY=/usr/lib64/libpython3.9.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.9 -DWITH_MPI=ON -DWITH_HEPMC=ON -DBUILD_FS_MODELS="CMSSM;MSSM;MDM" -Ditch="Cosmo;Neutrino;great" -DEIGEN3_INCLUDE_DIR=/mn/fys-server1/a1/chrichan/Packages/Eigen/eigen3 ..
-    - name: Build required scanners
-      run: |
-        echo "Build scanners required for test runs"
-        cd BUILD
-        make -j28 diver
-        cmake ..
-    - name: Build required backends
-      run: |
-        echo "Building backends required for test runs"
-        cd BUILD
-        make pythia
-        make higgssignals
-        make nulike
-        make ATLAS_FullLikes
-        make susyhit
-        make heplike
-        make superiso
-        make rivet
-        make contur
-        echo "Running cmake again, since this is required for ColliderBit/pythia"
-        cmake ..
-    - name: Build Gambit
-      run: |
-        echo "Build GAMBIT."
-        cd BUILD
-        # Now build Gambit
-        make -j28 gambit
-    - name: Run ColliderBit_CMSSM.yaml
-      run: |
-        echo "Test run with ColliderBit_CMSSM.yaml"
-        ./gambit -f yaml_files/ColliderBit_CMSSM.yaml
-    - name: Run WC_lite.yaml
-      run: |
-        echo "Test run with WC_lite.yaml (no printing)"
-        sed -i "" 's/ hdf5/ none/g' yaml_files/WC_lite.yaml
-        ./gambit -f yaml_files/WC_lite.yaml
+  # test_runs:
+  #   needs: [pre_job, gambit_build, backends_build] # Sets run order
+  #   if: ${{ !cancelled() && needs.pre_job.outputs.should_skip != 'true' }}
+  #   runs-on: [self-hosted, Linux, X64]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       arch: [X64]
+  #   defaults:
+  #     run:
+  #       shell: bash -eo pipefail {0}
+  #   steps:
+  #   - name: Checkout
+  #     uses: actions/checkout@v2
+  #   - name: Set up build environment
+  #     run: |
+  #       echo "Set up the build environment"
+  #       mkdir -p BUILD
+  #       cd BUILD
+  #       # The 'patch' tool is not installed system-wide on Wino, so we have our own installation of it:
+  #       alias patch=/mn/fys-server1/a9/anderkve/tools/patch/bin/patch
+  #   - name: Configure with cmake
+  #     run: |
+  #       echo "Configure with cmake"
+  #       cd BUILD
+  #       cmake -DPYTHON_LIBRARY=/usr/lib64/libpython3.9.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.9 -DWITH_MPI=ON -DWITH_HEPMC=ON -DBUILD_FS_MODELS="CMSSM;MSSM;MDM" -Ditch="Cosmo;Neutrino;great" -DEIGEN3_INCLUDE_DIR=/mn/fys-server1/a1/chrichan/Packages/Eigen/eigen3 ..
+  #   - name: Build required scanners
+  #     run: |
+  #       echo "Build scanners required for test runs"
+  #       cd BUILD
+  #       make -j28 diver
+  #       cmake ..
+  #   - name: Build required backends
+  #     run: |
+  #       echo "Building backends required for test runs"
+  #       cd BUILD
+  #       make pythia
+  #       make higgssignals
+  #       make nulike
+  #       make ATLAS_FullLikes
+  #       make susyhit
+  #       make heplike
+  #       make superiso
+  #       make rivet
+  #       make contur
+  #       echo "Running cmake again, since this is required for ColliderBit/pythia"
+  #       cmake ..
+  #   - name: Build Gambit
+  #     run: |
+  #       echo "Build GAMBIT."
+  #       cd BUILD
+  #       # Now build Gambit
+  #       make -j28 gambit
+  #   - name: Run ColliderBit_CMSSM.yaml
+  #     run: |
+  #       echo "Test run with ColliderBit_CMSSM.yaml"
+  #       ./gambit -f yaml_files/ColliderBit_CMSSM.yaml
+  #   - name: Run WC_lite.yaml
+  #     run: |
+  #       echo "Test run with WC_lite.yaml (no printing)"
+  #       sed -i "" 's/ hdf5/ none/g' yaml_files/WC_lite.yaml
+  #       ./gambit -f yaml_files/WC_lite.yaml
 
 
-  standalones_build:
-    needs: [pre_job, gambit_build, backends_build, test_runs] # Sets run order
-    if: ${{ always() && needs.pre_job.outputs.should_skip != 'true' }}
-    runs-on: [self-hosted, Linux, X64]
-    strategy:
-      fail-fast: false
-      matrix:
-        arch: [X64]
-    defaults:
-      run:
-        shell: bash -eo pipefail {0}
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v2
-    - name: Set up build environment
-      run: |
-        echo "Set up the build environment"
-        mkdir -p BUILD
-        cd BUILD
-        # The 'patch' tool is not installed system-wide on Wino, so we have our own installation of it:
-        alias patch=/mn/fys-server1/a9/anderkve/tools/patch/bin/patch
-    - name: Configure with cmake
-      run: |
-        echo "Configure with cmake"
-        cd BUILD
-        cmake -DPYTHON_LIBRARY=/usr/lib64/libpython3.9.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.9 -DWITH_MPI=ON -DWITH_HEPMC=ON -DBUILD_FS_MODELS="CMSSM;MSSM;MDM" -Ditch="great" -DEIGEN3_INCLUDE_DIR=/mn/fys-server1/a1/chrichan/Packages/Eigen/eigen3 ..
-    - name: Build standalones
-      run: |
-        echo "Test the building of the standalones"
-        cd BUILD
-        make standalones
+  # standalones_build:
+  #   needs: [pre_job, gambit_build, backends_build, test_runs] # Sets run order
+  #   if: ${{ !cancelled() && needs.pre_job.outputs.should_skip != 'true' }}
+  #   runs-on: [self-hosted, Linux, X64]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       arch: [X64]
+  #   defaults:
+  #     run:
+  #       shell: bash -eo pipefail {0}
+  #   steps:
+  #   - name: Checkout
+  #     uses: actions/checkout@v2
+  #   - name: Set up build environment
+  #     run: |
+  #       echo "Set up the build environment"
+  #       mkdir -p BUILD
+  #       cd BUILD
+  #       # The 'patch' tool is not installed system-wide on Wino, so we have our own installation of it:
+  #       alias patch=/mn/fys-server1/a9/anderkve/tools/patch/bin/patch
+  #   - name: Configure with cmake
+  #     run: |
+  #       echo "Configure with cmake"
+  #       cd BUILD
+  #       cmake -DPYTHON_LIBRARY=/usr/lib64/libpython3.9.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.9 -DWITH_MPI=ON -DWITH_HEPMC=ON -DBUILD_FS_MODELS="CMSSM;MSSM;MDM" -Ditch="great" -DEIGEN3_INCLUDE_DIR=/mn/fys-server1/a1/chrichan/Packages/Eigen/eigen3 ..
+  #   - name: Build standalones
+  #     run: |
+  #       echo "Test the building of the standalones"
+  #       cd BUILD
+  #       make standalones
